---
title: "Differential Gene Expression and Enrichment Analysis"
author: Jade Sha
date: Sep 13, 2021
output: html_document
---
# load pakages
```{r setup, message=FALSE}
library(readr)
library(dplyr)
library(tibble)
library(edgeR)
library(readr)
library(clusterProfiler)
library(scater)
library(bbcRNA)
orgdb <- "org.Hs.eg.db" 
library(orgdb, character.only=TRUE) # load the org.db for your organism
library(AnnotationDbi)
library(tibble)
library(DOSE)
library(msigdbr)
library("pathview")
```
# DE
```{r load_files, include=TRUE}
load("./allgenes.Rdata")
load("./genelistfiles.Rdata")
head(meta_df)
head(y)

## run base model
design2 <- model.matrix(~0+group+sex+age, data = y$samples)
design2

y2 <- estimateDisp(y, design2, robust=TRUE)
plotBCV(y2, main=paste0("BCV plot"))

fit2 <- glmQLFit(y2, design2, robust=TRUE)
plotQLDisp(fit2, main=paste0("QLDisp plot"))

contrasts <- makeContrasts("groupMDD-groupCT", levels=design2)
contrasts

res2 <- glmQLFTest(fit2, contrast=contrasts)
topTags(res2)

##save results
save.res=topTags(res2,  n = Inf)
write_tsv(as.data.frame(save.res), paste0("DE", "/","glmQLFtest5sexage.tsv"))

is.de <- decideTestsDGE(res2)
summary(is.de)
plotMD(res2, status=is.de, values=c(1,-1), col=c("red","blue"),
       legend="topright")

save(y2, design2, res2, file = "./model_w_sexage.Rdata")

```

# Pathway analysis
``` {r make_genelist}
all_tags <- topTags(res2, n = Inf) %>% as.data.frame()
genList2 <- all_tags$logFC
head(genList2)
names(genList2) <- all_tags$entrez
head(genList2)
genList2 = genList2[which(!is.na(names(genList2)))]
genList2 = genList2[!duplicated(names(genList2))]
genList2 <- sort(genList2, decreasing = T)
head(genList2)
save(genList2, file = "./genList2.Rdata")
```


# GSEA 
```{r GSEA, message=FALSE, warning=FALSE, fig.show='hide'}

## category Hallmark genes
Hall <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, entrez_gene)
head(Hall)

emhall <- GSEA(genList2, TERM2GENE = Hall )

gseaHALL_export <-emhall %>% as.data.frame()
head(emhall, 10)
write_tsv(gseaHALL_export, paste0("gsea","/","gseaHALL_export_sexage.tsv"))

### dotplot
dotplot(emhall, showCategory=30)+ggtitle("dotplot for GSEA")

### cnetplot
edox <- setReadable(emhall, 'org.Hs.eg.db', 'ENTREZID')
p1 <- cnetplot(edox, node_label="category", 
               cex_label_category = 1.0)
p2 <- cnetplot(edox, node_label="gene", 
               cex_label_gene = 0.6) 
p1
p2

## category Curated genes
c2 <- msigdbr(species = "Homo sapiens", category = "C2") %>% 
  dplyr::select(gs_name, entrez_gene)
head(c2)

emc2 <- GSEA(genList2, TERM2GENE = c2 )

gseaC2_export <-emc2 %>% as.data.frame()
head(emc2, 5)
write_tsv(gseaC2_export, paste0("gsea","/","gseaC2_export_sexage.tsv"))

### dotplot
dotplot(emc2, showCategory=30)+ggtitle("dotplot for GSEA")

### cnetplot
edox <- setReadable(emc2, 'org.Hs.eg.db', 'ENTREZID')
p1 <- cnetplot(edox, node_label="category", 
               cex_label_category = 1.0)
p2 <- cnetplot(edox, node_label="gene", 
               cex_label_gene = 0.6) 
p1
p2

## category Ontology genes
c5 <- msigdbr(species = "Homo sapiens", category = "C5") %>% 
  dplyr::select(gs_name, entrez_gene)
head(c5)

emc5 <- GSEA(genList2, TERM2GENE = c5 )

gseaC5_export <-emc5 %>% as.data.frame()
head(emc5, 5)
write_tsv(gseaC5_export, paste0("gsea","/","gseaC5_export_sexage.tsv"))

### dotplot
dotplot(emc5, showCategory=30)+ggtitle("dotplot for GSEA")

### cnetplot
edox <- setReadable(emc5, 'org.Hs.eg.db', 'ENTREZID')
p1 <- cnetplot(edox, node_label="category", 
               cex_label_category = 1.0)
p2 <- cnetplot(edox, node_label="gene", 
               cex_label_gene = 0.6) 
p1
p2

## category Immunlogic genes
c7 <- msigdbr(species = "Homo sapiens", category = "C7") %>% 
  dplyr::select(gs_name, entrez_gene)
head(c7)

emc7 <- GSEA(genList2, TERM2GENE = c7 )

gseaC7_export <-emc7 %>% as.data.frame()
head(emc7, 5)
write_tsv(gseaC7_export, paste0("gsea","/","gseaC7_export_sexage.tsv"))

### dotplot
dotplot(emc7, showCategory=30)+ggtitle("dotplot for GSEA")

### cnetplot
edox <- setReadable(emc7, 'org.Hs.eg.db', 'ENTREZID')
p1 <- cnetplot(edox, node_label="category", 
               cex_label_category = 1.0)
p2 <- cnetplot(edox, node_label="gene", 
               cex_label_gene = 0.6) 
p1
p2


```

# Kegg analysis

```{r Kegg, message=FALSE, warning=FALSE}
kk <- gseKEGG(geneList = genList2,
              organism = 'hsa',
              minGSSize = 10, 
              maxGSSize = 1000,
              pvalueCutoff = 1.0,
              eps = 0, 
              verbose = F)

head(kk)
write_tsv(as.data.frame(kk), paste0("gsea", "/","Kegg5_sexage.tsv"))

hsa04213 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa04213",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
hsa04915 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa04915",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
hsa04141 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa0141",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
hsa04610 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa04610",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
hsa03040 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa03040",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
hsa04145 <- pathview(gene.data  = genList2,
                     pathway.id = "hsa04145",
                     species    = "hsa",
                     limit      = list(gene=max(abs(genList2)), cpd=1))
```

# GO analysis
```{r GO_analysi}
head(genList2)
gene <- names(genList2)[abs(genList2) > 2]
head(gene)
ego <- enrichGO(gene          = gene,
                universe      = names(genList2),
                OrgDb         = 'org.Hs.eg.db',
                ont           = "ALL",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
head(ego)
write_tsv(as.data.frame(ego), paste0("gsea", "/","GOenchrich_sexage.tsv"))


```



