---
title: "Make_files_for_DE"
author: Jade Sha
date: Sep, 2021
output: html_document
---


```{r setup, message=FALSE}
library(readr)
library(dplyr)
library(tibble)
library(edgeR)
library(readr)
library(clusterProfiler)
library(scater)
library(bbcRNA)
orgdb <- "org.Hs.eg.db" 
library(orgdb, character.only=TRUE) # load the org.db for your organism
library(AnnotationDbi)
library(tibble)
```


# load seqs
```{r make_files}
base <- ("../RNAseq_star/")

genecounts <- star_to_mat(dir = file.path(base), 
                     rgx = "^S[:alnum:]+", column = 3)
head(genecounts)

## add gene symbols
gene_names_df <- data.frame(row.names = rownames(genecounts))
gene_names_df$Symbol <- AnnotationDbi::mapIds(eval(as.name(orgdb)), 
                                              rownames(gene_names_df), 
                                              keytype="ENSEMBL", column="SYMBOL", 
                                              multiVals="first")
gene_names_df$Uniq_syms <- scater::uniquifyFeatureNames(rownames(gene_names_df),
                                                        gene_names_df$Symbol)
gene_names_df$entrez <- AnnotationDbi::mapIds(eval(as.name(orgdb)), rownames(gene_names_df), 
                                              keytype="ENSEMBL", column="ENTREZID", 
                                              multiVals="first") # there are duplicates in here.

raw_counts_df <- gene_names_df %>% 
  rownames_to_column("ensembl_id") %>% 
  left_join(., as_tibble(genecounts, rownames="ensembl_id"), by="ensembl_id") 
write_rds(raw_counts_df, paste0("data","/","raw_counts.rds"))
write_tsv(raw_counts_df, paste0("data","/","raw_counts.tsv"))

head(gene_names_df)
head(raw_counts_df)
save(genecounts, gene_names_df, file = "./allgenes.Rdata")

#load("./allgenes.Rdata")
```

# Diferential anlaysis
```{r DE}
load("./allgenes.Rdata")
meta_df <- read.csv("../fulldata0824221.csv") %>% as.data.frame()
rownames(meta_df) <- NULL

rownames(meta_df) <- meta_df$HNCID
meta_df$group <- as.factor(meta_df$group)

## next, adjust the order of meta_df
rownames(meta_df) == colnames(genecounts)

meta_df <- meta_df[colnames(genecounts), ]
rownames(meta_df) == colnames(genecounts)

head(meta_df)

## create DGElist
head(gene_names_df)
y <- DGEList(genecounts, samples = meta_df, 
             genes = gene_names_df, group = meta_df$group ) 

head(y)
keep <- rowSums(edgeR::cpm(y$counts) > 0.5) >= 5
table(keep) 

y <- y[keep, , keep.lib.sizes=FALSE]
y <- calcNormFactors(y)

norm_counts <- edgeR::cpm(y, log=TRUE)

## export count data, which are normalized and CPM, note here, log transformation is log2 based. 
#getwd()
#setwd("/Users/jade.sha/Documents/RO1/John_Mann_Brain_RNAseq/R code/")
norm_counts_df <- y$genes %>% 
  rownames_to_column("ensembl_id") %>% 
  left_join(., as_tibble(norm_counts, rownames="ensembl_id"), by="ensembl_id") 

write_rds(norm_counts_df, paste0("data", "/","norm_counts5.rds"))
write_tsv(norm_counts_df, paste0("data", "/","norm_counts5.tsv"))

##run model
design1 <- model.matrix(~0+group, data = y$samples)
design1

y1 <- estimateDisp(y, design1, robust=TRUE)
plotBCV(y1, main=paste0("BCV plot"))

fit1 <- glmQLFit(y1, design, robust=TRUE)
plotQLDisp(fit1, main=paste0("QLDisp plot")) ##Plot the quasi-likelihood dispersion

contrasts <- makeContrasts("groupMDD-groupCT", levels=design1)
contrasts

res1 <- glmQLFTest(fit1, contrast=contrasts)
#res1
topTags(res1)
##save results
save.res=topTags(res1)
write_tsv(as.data.frame(save.res), paste0("DE", "/","glmQLFtest5.tsv"))

is.de <- decideTestsDGE(res1)
summary(is.de)
plotMD(res, status=is.de, values=c(1,-1), col=c("red","blue"),
       legend="topright")

```




